# Generated by Django 5.2.17 on 2026-08-29 14:52

import django.db.models.deletion
import meetings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='allow_before_host',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='meeting',
            name='mute_on_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='require_auth',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='waiting_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingparticipant',
            name='hand_raised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingparticipant',
            name='is_camera_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingparticipant',
            name='is_muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meetingparticipant',
            name='role',
            field=models.CharField(choices=[('host', 'Host'), ('cohost', 'Co-Host'), ('participant', 'Participant')], default='participant', max_length=20),
        ),
        migrations.CreateModel(
            name='ScheduledMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('meeting_code', models.CharField(default=meetings.models.generate_meeting_code, max_length=20)),
                ('waiting_room', models.BooleanField(default=False)),
                ('require_auth', models.BooleanField(default=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_meetings', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_instance', to='meetings.meeting')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
